#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Jul 10, 2021 01:22:25 PM CAT  platform: Windows NT

import sys

from tkinter import filedialog
import page2
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import mainPage_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    mainPage_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    mainPage_support.init(w, top, *args, **kwargs)
    return(w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        self.fileName = "NONE"

        top.geometry("818x530+246+103")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("CartooniZe")
        top.configure(borderwidth="1")
        top.configure(background="#ffffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.815, rely=0.047, height=34, width=107)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#fa6400")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI Symbol} -size 10")
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Get Started''')

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.685, rely=0.057, height=25, width=85)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI Symbol} -size 11")
        self.Label1.configure(foreground="#353535")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Learn''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.575, rely=0.057, height=25, width=85)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#ffffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI Symbol} -size 11")
        self.Label2.configure(foreground="#353535")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Features''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.141, rely=0.357, height=95, width=614)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="#000000")
        self.Label3.configure(background="#ffffff")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.Label3.configure(foreground="#2a2a2a")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Convert Photo into Cartoon Drawing .''')

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.183, rely=0.509, height=65, width=553)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#ffffff")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI} -size 10")
        self.Label4.configure(foreground="#696969")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Transform any picture into a cartoon in a few simple steps . Learn how to use cartoonize to easily add creative cartoon photo effects to your image .''')
        self.Label4.configure(wraplength="550")

        self.Button2 = tk.Button(top, command=self.fileDailog)
        self.Button2.place(relx=0.295, rely=0.732, height=34, width=127)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#fa6400")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Button2.configure(foreground="#ffffff")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Upload Photo''')

        self.LabelFrame = tk.LabelFrame(top, text="Your chosen image path")
        self.LabelFrame.grid(column=0, row=1, padx=20, pady=20)
        self.LabelFrame.configure(background="#fa6400")
        self.LabelFrame.configure(font="-family {Segoe UI} -size 11 -weight bold")


        self.Button3 = tk.Button(top, command=self.move_to_page2)
        self.Button3.place(relx=0.562, rely=0.732, height=34, width=127)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#fa6400")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Button3.configure(foreground="#ffffff")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Cartoonize''')

    def fileDailog(self):
        self.fileName = filedialog.askopenfilename(initialdir="/", title="Select A File",
                                                   filetype=(("jpeg", "*.jpg"), ("png", "*.png")))
        self.label = ttk.Label(self.LabelFrame, text="")
        self.label.grid(column=1, row=2)
        self.label.configure(text=self.fileName)

    def move_to_page2(self):
        page2.create_Toplevel1(root, self.fileName)

if __name__ == '__main__':
    vp_start_gui()





